### PR TITLE
Fixes an issue with passman

### PR DESCRIPTION
**Pull request by irule311**
Passman app was showing white on white. This fixes it.

### CODE REVIEW

**Comment by mwalbeck** [comment]
Thank you for your contribution.

Sadly doing this might cause problems elsewhere. It's been awhile since I last styled some of the components so I can't say for sure what parts. But I had a quick look at Passman and it should be fairly straight forward to style, so I'll be doing that instead.

I'll also be opening an Issue with a list of the apps I have styled and which I currently plan to style. If there is an app you use which is not on the list please let me know and I'll add it.

**Comment by mwalbeck** [comment]
I've pushed an update to the master branch with styling for Passman, so if you update the theme it should be all good. Let me know if you run into any other issues.

**Comment by irule311** [comment]
Wow thanks for the fast update. This is awesome. I'm a noob at css, so I just has some trial and error with the css code. 

There is an issue with the personal and admin setting when viewing as a mobile device. When simulated in chrome or on an actual device, the background become white. Any ideas on this?
Thanks!
capture

**Comment by mwalbeck** [comment]
Thanks for letting me know.

I've pushed a new update which should fix it.

**Comment by irule311** [comment]
Great work! I have just 2 more small issues. 

The folder names are a little dark and hard to read. Would it be possible to make this a lighter grey or even white?
capture

Also would it be possible to make this close icon glow or something to make it stand out in all images?
capture11

Sometimes it turns invisible when there is a white background on it like here.
capture12

Finally, its not incredibly significant, but the background of a logged item turns white when selecting and dragging.
2017-04-21 15_39_26-admin - storage

Thanks for the great work again.

**Comment by mwalbeck** [comment]
fixed

**Pull request closed without merging**
