### PR TITLE
Add support for NC28

### LINKED ISSUE #339: Update to NC28 please
Could you update this app to be compatible with NC28?
Thanks

### PR DESCRIPTION
**Pull request by darkfishy**
Fixes #339 
Doesn't seem to break anything on our prod install.
@mwalbeck Please review.

### CODE REVIEW

**Comment by darkfishy** [comment]
No JS or CSS files have been modified, so I suspect that the checks are failing on master too.

**Comment by IgorA100** [comment]
@mwalbeck @darkfishy
Why was NC27 support disabled?
I think we should have left NC27 support and added NC28

**Comment by mwalbeck** [comment]
> @mwalbeck @darkfishy Why was NC27 support disabled? I think we should have left NC27 support and added NC28

It's just how the versioning for the theme is set up, so v27 of the theme only supports v27 of NC and so on. That's also why there is a branch for each major version of the theme, so updates can still be made to previous releases if necessary. I've done it quite a bit in the past, backporting changes whenever they were applicable to the previous release of the theme.

The reason for why I set it up this way, is not as applicable any more, but there used to be quite a lot of changes needed between major Nextcloud releases to support the next release. So it was quite a lot easier to make completely separate releases of the theme instead of trying to make them compatible with each other.

**Comment by IgorA100** [comment]
Thanks I got it.

**Pull request merged**
