### PR TITLE
Fix styling of sidebar for Tasks

### PR DESCRIPTION
**Pull request by Georgeto**
The sidebar is not (no longer?) a subelement of #app-content.

### CODE REVIEW

**Comment by mwalbeck** [comment]
Hi,

Thank you for your pull request. I appreciate the help, keeping an eye on everything. yeah it seems they moved the #app-sidebar out of #app-content. I haven't had a good look at tasks in a long time, but it's currently high on the list of apps that need an overhaul.

Sadly there is one small little problem with your pull request. You haven't compiled the sass changes into the server.css file. It would be great if you could compile and commit the changes, then I can merge them. If you have any questions regarding Sass, be sure to ask and I'll do my best to help.

**Comment by Georgeto** [comment]
> If you have any questions regarding Sass, be sure to ask and I'll do my best to help.

Which sass implementation do you use? Using the [official](https://sass-lang.com/dart-sass) implementation, I tested with various versions of it, results in a large amount of changes spread over the whole file.

**Comment by mwalbeck** [comment]
Okay, I have taken a look at it and the ruby implementation of sass is on life support in favor of the dart implementation (the new official one), so with that in mind I'm going to switch to using the latest dart implementation of sass instead. I'm going to push a quick update to the develop branch with the newly compiled server.css.

**Comment by Georgeto** [comment]
Thank you. I rebased onto the updated develop branch, and compiled the `server.scss`.

**Comment by mwalbeck** [comment]
Great. Thank you for the contribution.

**Pull request merged**
