### PR TITLE
Glowing close button and white navigation text

### PR DESCRIPTION
**Pull request by irule311**
This should fix the invisible close button by adding a black drop shadow.
capture11

It also should fix this issue.
capture

### CODE REVIEW

**Comment by mwalbeck** [comment]
Thank you for all your reporting of issues, I appreciate it a lot.

Now I've only just added some info about contributions to the README so some of the following is partly my fault for not having set up proper guidelines for contributions.

First things first, future pull request should be made to the develop branch instead of master.

The CSS is good but I've some specific colours I use for this theme which are taken from the Breeze Dark theme made by the KDE folks, and I would like to stick to those colours. Also for this theme I've have used Sass instead of pure CSS, so all styling is written in the .scss files and compiled to .css files. There is a link to read more about Sass in the README.

I originally remove the shadow from the X because I didn't feel the shadow really fit that well with the theme, but I can see the problem it creates. I'll see if I can think of anything better but if not then I'll switch out the X. I still have the old X lying around where the shadow is in a x shape as well, which looks a bit better than the square shadow.

If you would like to make changes to the breadcrumb folder name in Sass you're very welcome to do so. You'll find the colours in the _colours.scss file and the styling for should go in the apps/files.scss file since these changes are specific to the files app.

Lastly, I'm still figuring out the exact guidelines for contributing and how the code guidelines but for know there is a bare bones version in the README. If you have any questions then please let me know.

**Comment by irule311** [comment]
Thanks for the info. I'm a beginner to all of this so I achieved this just from poking around in the chrome developer console. I have no actual experience developing in css, let alone sass. Github is also new to me as you may have seen from the random closed pull requests I made lol.

For the X, it may be possible to increase the dimensions of the svc outline and add a drop shadow with a larger blur so its not as square-like. I'll see what I can do about that. 

Do you think you would be able to implement the patch here in sass and push it to the master branch?

Finally, there is the weird white background with logs that I haven't been able to figure out yet. Any ideas on this?
2017-04-21 15_39_26-admin - storage

**Comment by mwalbeck** [comment]
Yeah, I noticed the pull requests hehe. I just wanted to make sure we were some what on the same page.

Now for the theme issues, those should be fairly straight forward so no problem there. With the X, as I noted, I already have one that looks good, which I borrowed from the standard Nextcloud theme, just with the colours flipped.

**Comment by mwalbeck** [comment]
Fixed css issues and added X with shadow.

**Pull request closed without merging**
